### ISSUE TITLE
TypeError: str.trimEnd is not a function

### ISSUE THREAD

**Issue by madoar** [earshinov/extract-scss-variables#1]
When building `angular-archwizard` I get the following error message:

```
> angular-archwizard@4.1.0-develop extract-scss-variables /home/marc/git/angular-archwizard
> node node_modules/@earshinov/extract-scss-variables/bin/extract-scss-variables ./dist/archwizard.scss ./dist/variables.scss

/home/marc/git/angular-archwizard/node_modules/@earshinov/extract-scss-variables/dist/index.js:83
            str = `${str.trimEnd()}\n`;
                         ^

TypeError: str.trimEnd is not a function
    at Object.finalizeContent (/home/marc/git/angular-archwizard/node_modules/@earshinov/extract-scss-variables/dist/index.js:83:26)
    at extractScssVariables (/home/marc/git/angular-archwizard/node_modules/@earshinov/extract-scss-variables/dist/index.js:94:33)
    at main (/home/marc/git/angular-archwizard/node_modules/@earshinov/extract-scss-variables/bin/extract-scss-variables.js:32:5)
    at Object.<anonymous> (/home/marc/git/angular-archwizard/node_modules/@earshinov/extract-scss-variables/bin/extract-scss-variables.js:36:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
```

**Comment by earshinov** [comment]
@madoar , Thanks for reporting! I have incorrectly set "engines" in package.json to "nodejs >= 8". The correct value should be "nodejs >= 10" (the current LTS version). I hope it is acceptable for you to use NodeJS 10.x?
